/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ShipEngine.ApiClient.Client;
using ShipEngine.ApiClient.Model;

namespace ShipEngine.ApiClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INLPApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>RecognizeAddressResponseDTO</returns>
        RecognizeAddressResponseDTO NLPRecognizeAddress (RecognizeAddressRequestDTO body);

        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of RecognizeAddressResponseDTO</returns>
        ApiResponse<RecognizeAddressResponseDTO> NLPRecognizeAddressWithHttpInfo (RecognizeAddressRequestDTO body);
        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>RecognizeShipmentResponseDTO</returns>
        RecognizeShipmentResponseDTO NLPRecognizeShipment (RecognizeShipmentRequestDTO body);

        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of RecognizeShipmentResponseDTO</returns>
        ApiResponse<RecognizeShipmentResponseDTO> NLPRecognizeShipmentWithHttpInfo (RecognizeShipmentRequestDTO body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of RecognizeAddressResponseDTO</returns>
        System.Threading.Tasks.Task<RecognizeAddressResponseDTO> NLPRecognizeAddressAsync (RecognizeAddressRequestDTO body);

        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (RecognizeAddressResponseDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<RecognizeAddressResponseDTO>> NLPRecognizeAddressAsyncWithHttpInfo (RecognizeAddressRequestDTO body);
        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of RecognizeShipmentResponseDTO</returns>
        System.Threading.Tasks.Task<RecognizeShipmentResponseDTO> NLPRecognizeShipmentAsync (RecognizeShipmentRequestDTO body);

        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (RecognizeShipmentResponseDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<RecognizeShipmentResponseDTO>> NLPRecognizeShipmentAsyncWithHttpInfo (RecognizeShipmentRequestDTO body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NLPApi : INLPApi
    {
        private ShipEngine.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NLPApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NLPApi(String basePath)
        {
            this.Configuration = new ShipEngine.ApiClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ShipEngine.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NLPApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NLPApi(ShipEngine.ApiClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ShipEngine.ApiClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ShipEngine.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ShipEngine.ApiClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ShipEngine.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>RecognizeAddressResponseDTO</returns>
        public RecognizeAddressResponseDTO NLPRecognizeAddress (RecognizeAddressRequestDTO body)
        {
             ApiResponse<RecognizeAddressResponseDTO> localVarResponse = NLPRecognizeAddressWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of RecognizeAddressResponseDTO</returns>
        public ApiResponse< RecognizeAddressResponseDTO > NLPRecognizeAddressWithHttpInfo (RecognizeAddressRequestDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling NLPApi->NLPRecognizeAddress");

            var localVarPath = "/v1/addresses/recognize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (api-key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api-key")))
            {
                localVarHeaderParams["api-key"] = this.Configuration.GetApiKeyWithPrefix("api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NLPRecognizeAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RecognizeAddressResponseDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RecognizeAddressResponseDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RecognizeAddressResponseDTO)));
        }

        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of RecognizeAddressResponseDTO</returns>
        public async System.Threading.Tasks.Task<RecognizeAddressResponseDTO> NLPRecognizeAddressAsync (RecognizeAddressRequestDTO body)
        {
             ApiResponse<RecognizeAddressResponseDTO> localVarResponse = await NLPRecognizeAddressAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Identifies address-related entities (name, line1, line2, city, postal code, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (RecognizeAddressResponseDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RecognizeAddressResponseDTO>> NLPRecognizeAddressAsyncWithHttpInfo (RecognizeAddressRequestDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling NLPApi->NLPRecognizeAddress");

            var localVarPath = "/v1/addresses/recognize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (api-key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api-key")))
            {
                localVarHeaderParams["api-key"] = this.Configuration.GetApiKeyWithPrefix("api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NLPRecognizeAddress", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RecognizeAddressResponseDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RecognizeAddressResponseDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RecognizeAddressResponseDTO)));
        }

        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>RecognizeShipmentResponseDTO</returns>
        public RecognizeShipmentResponseDTO NLPRecognizeShipment (RecognizeShipmentRequestDTO body)
        {
             ApiResponse<RecognizeShipmentResponseDTO> localVarResponse = NLPRecognizeShipmentWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of RecognizeShipmentResponseDTO</returns>
        public ApiResponse< RecognizeShipmentResponseDTO > NLPRecognizeShipmentWithHttpInfo (RecognizeShipmentRequestDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling NLPApi->NLPRecognizeShipment");

            var localVarPath = "/v1/shipments/recognize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (api-key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api-key")))
            {
                localVarHeaderParams["api-key"] = this.Configuration.GetApiKeyWithPrefix("api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NLPRecognizeShipment", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RecognizeShipmentResponseDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RecognizeShipmentResponseDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RecognizeShipmentResponseDTO)));
        }

        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of RecognizeShipmentResponseDTO</returns>
        public async System.Threading.Tasks.Task<RecognizeShipmentResponseDTO> NLPRecognizeShipmentAsync (RecognizeShipmentRequestDTO body)
        {
             ApiResponse<RecognizeShipmentResponseDTO> localVarResponse = await NLPRecognizeShipmentAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Identifies shipment-related entities (names, address parts, package dimensions, weight, insurance options, etc.) in unstructured text  
        /// </summary>
        /// <exception cref="ShipEngine.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (RecognizeShipmentResponseDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RecognizeShipmentResponseDTO>> NLPRecognizeShipmentAsyncWithHttpInfo (RecognizeShipmentRequestDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling NLPApi->NLPRecognizeShipment");

            var localVarPath = "/v1/shipments/recognize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (api-key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api-key")))
            {
                localVarHeaderParams["api-key"] = this.Configuration.GetApiKeyWithPrefix("api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NLPRecognizeShipment", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RecognizeShipmentResponseDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RecognizeShipmentResponseDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RecognizeShipmentResponseDTO)));
        }

    }
}
