/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ShipEngine.ApiClient.Client.SwaggerDateConverter;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    /// StampsAccountUrlsRequest
    /// </summary>
    [DataContract]
    public partial class StampsAccountUrlsRequest :  IEquatable<StampsAccountUrlsRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines UrlTypes
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UrlTypesEnum
        {
            
            /// <summary>
            /// Enum AccountSettings for value: accountSettings
            /// </summary>
            [EnumMember(Value = "accountSettings")]
            AccountSettings = 1,
            
            /// <summary>
            /// Enum ReportBalances for value: reportBalances
            /// </summary>
            [EnumMember(Value = "reportBalances")]
            ReportBalances = 2,
            
            /// <summary>
            /// Enum ManifestForm for value: manifestForm
            /// </summary>
            [EnumMember(Value = "manifestForm")]
            ManifestForm = 3,
            
            /// <summary>
            /// Enum PaymentMethods for value: paymentMethods
            /// </summary>
            [EnumMember(Value = "paymentMethods")]
            PaymentMethods = 4
        }


        /// <summary>
        /// Gets or Sets UrlTypes
        /// </summary>
        [DataMember(Name="url_types", EmitDefaultValue=false)]
        public List<UrlTypesEnum> UrlTypes { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StampsAccountUrlsRequest" /> class.
        /// </summary>
        /// <param name="urlTypes">urlTypes.</param>
        public StampsAccountUrlsRequest(List<UrlTypesEnum> urlTypes = default(List<UrlTypesEnum>))
        {
            this.UrlTypes = urlTypes;
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StampsAccountUrlsRequest {\n");
            sb.Append("  UrlTypes: ").Append(UrlTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StampsAccountUrlsRequest);
        }

        /// <summary>
        /// Returns true if StampsAccountUrlsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of StampsAccountUrlsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StampsAccountUrlsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UrlTypes == input.UrlTypes ||
                    this.UrlTypes != null &&
                    this.UrlTypes.SequenceEqual(input.UrlTypes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UrlTypes != null)
                    hashCode = hashCode * 59 + this.UrlTypes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
