/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ShipEngine.ApiClient.Client.SwaggerDateConverter;

namespace ShipEngine.ApiClient.Model
{
    /// <summary>
    /// StampsAccountUrlResponse
    /// </summary>
    [DataContract]
    public partial class StampsAccountUrlResponse :  IEquatable<StampsAccountUrlResponse>, IValidatableObject
    {
        /// <summary>
        /// Defines UrlType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UrlTypeEnum
        {
            
            /// <summary>
            /// Enum AccountSettings for value: accountSettings
            /// </summary>
            [EnumMember(Value = "accountSettings")]
            AccountSettings = 1,
            
            /// <summary>
            /// Enum ReportBalances for value: reportBalances
            /// </summary>
            [EnumMember(Value = "reportBalances")]
            ReportBalances = 2,
            
            /// <summary>
            /// Enum ManifestForm for value: manifestForm
            /// </summary>
            [EnumMember(Value = "manifestForm")]
            ManifestForm = 3,
            
            /// <summary>
            /// Enum PaymentMethods for value: paymentMethods
            /// </summary>
            [EnumMember(Value = "paymentMethods")]
            PaymentMethods = 4
        }

        /// <summary>
        /// Gets or Sets UrlType
        /// </summary>
        [DataMember(Name="url_type", EmitDefaultValue=false)]
        public UrlTypeEnum? UrlType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StampsAccountUrlResponse" /> class.
        /// </summary>
        /// <param name="urlType">urlType.</param>
        /// <param name="url">url.</param>
        public StampsAccountUrlResponse(UrlTypeEnum? urlType = default(UrlTypeEnum?), string url = default(string))
        {
            this.UrlType = urlType;
            this.Url = url;
        }
        

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StampsAccountUrlResponse {\n");
            sb.Append("  UrlType: ").Append(UrlType).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StampsAccountUrlResponse);
        }

        /// <summary>
        /// Returns true if StampsAccountUrlResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StampsAccountUrlResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StampsAccountUrlResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UrlType == input.UrlType ||
                    (this.UrlType != null &&
                    this.UrlType.Equals(input.UrlType))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UrlType != null)
                    hashCode = hashCode * 59 + this.UrlType.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
