/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ShipEngine.ApiClient.Client;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing CarrierAccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CarrierAccountsApiTests
    {
        private CarrierAccountsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CarrierAccountsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierAccountsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CarrierAccountsApi
            //Assert.IsInstanceOfType(typeof(CarrierAccountsApi), instance, "instance is a CarrierAccountsApi");
        }

        
        /// <summary>
        /// Test AccessWorldwideAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void AccessWorldwideAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AccessWorldwideAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.AccessWorldwideAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test AccessWorldwideAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void AccessWorldwideAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.AccessWorldwideAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test ApcAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void ApcAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ApcAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.ApcAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test ApcAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void ApcAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.ApcAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test AsendiaAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void AsendiaAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AsendiaAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.AsendiaAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test AsendiaAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void AsendiaAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.AsendiaAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test DHLECommerceAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void DHLECommerceAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DHLECommerceAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.DHLECommerceAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test DHLECommerceAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void DHLECommerceAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.DHLECommerceAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test DHLExpressAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void DHLExpressAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DHLExpressAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.DHLExpressAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test DHLExpressAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void DHLExpressAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.DHLExpressAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test DHLExpressAccountCarrierGetSettings
        /// </summary>
        [Test]
        public void DHLExpressAccountCarrierGetSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //var response = instance.DHLExpressAccountCarrierGetSettings(carrierId, apiKey);
            //Assert.IsInstanceOf<DHLExpressAccountSettingsDTO> (response, "response is DHLExpressAccountSettingsDTO");
        }
        
        /// <summary>
        /// Test DHLExpressAccountCarrierUpdateSettings
        /// </summary>
        [Test]
        public void DHLExpressAccountCarrierUpdateSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //DHLExpressAccountSettingsDTO settings = null;
            //string apiKey = null;
            //instance.DHLExpressAccountCarrierUpdateSettings(carrierId, settings, apiKey);
            
        }
        
        /// <summary>
        /// Test DHLExpressCaAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void DHLExpressCaAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DHLExpressCaAccountInformationRequest model = null;
            //string apiKey = null;
            //var response = instance.DHLExpressCaAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test DHLExpressCaAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void DHLExpressCaAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.DHLExpressCaAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test DhlExpressUkAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void DhlExpressUkAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DHLExpressUkAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.DhlExpressUkAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test DhlExpressUkAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void DhlExpressUkAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.DhlExpressUkAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test DpdAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void DpdAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DpdAccountInformationRequest model = null;
            //string apiKey = null;
            //var response = instance.DpdAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test DpdAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void DpdAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.DpdAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test EndiciaAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void EndiciaAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EndiciaAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.EndiciaAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test EndiciaAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void EndiciaAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.EndiciaAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test FedExAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void FedExAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FedExAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.FedExAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test FedExAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void FedExAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.FedExAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test FedExAccountCarrierGetSettings
        /// </summary>
        [Test]
        public void FedExAccountCarrierGetSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //var response = instance.FedExAccountCarrierGetSettings(carrierId, apiKey);
            //Assert.IsInstanceOf<UPSAccountSettingsDTO> (response, "response is UPSAccountSettingsDTO");
        }
        
        /// <summary>
        /// Test FedExAccountCarrierUpdateSettings
        /// </summary>
        [Test]
        public void FedExAccountCarrierUpdateSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //FedExAccountSettingsDTO settings = null;
            //string apiKey = null;
            //instance.FedExAccountCarrierUpdateSettings(carrierId, settings, apiKey);
            
        }
        
        /// <summary>
        /// Test FedExUkAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void FedExUkAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FedExUkAccountInformationRequest model = null;
            //string apiKey = null;
            //var response = instance.FedExUkAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test FedExUkAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void FedExUkAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.FedExUkAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test FirstMileAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void FirstMileAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FirstMileAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.FirstMileAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test FirstMileAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void FirstMileAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.FirstMileAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test GlobegisticsAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void GlobegisticsAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GlobegisticsAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.GlobegisticsAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test GlobegisticsAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void GlobegisticsAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.GlobegisticsAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test ImexAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void ImexAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ImexAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.ImexAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test ImexAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void ImexAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.ImexAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test NewgisticsAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void NewgisticsAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NewgisticsAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.NewgisticsAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test NewgisticsAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void NewgisticsAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.NewgisticsAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test NewgisticsAccountCarrierUpdateSettings
        /// </summary>
        [Test]
        public void NewgisticsAccountCarrierUpdateSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //NewgisticsAccountSettingsDTO settings = null;
            //string apiKey = null;
            //instance.NewgisticsAccountCarrierUpdateSettings(carrierId, settings, apiKey);
            
        }
        
        /// <summary>
        /// Test OnTracAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void OnTracAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OnTracAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.OnTracAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test OnTracAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void OnTracAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.OnTracAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test PurolatorAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void PurolatorAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PurolatorAccountInformationRequest model = null;
            //string apiKey = null;
            //var response = instance.PurolatorAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test PurolatorAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void PurolatorAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.PurolatorAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test RoyalMailAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void RoyalMailAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RoyalMailAccountInformationRequest model = null;
            //string apiKey = null;
            //var response = instance.RoyalMailAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test RoyalMailAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void RoyalMailAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.RoyalMailAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test RrDonnelleyAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void RrDonnelleyAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RrDonnelleyAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.RrDonnelleyAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test RrDonnelleyAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void RrDonnelleyAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.RrDonnelleyAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test StampsAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void StampsAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StampsAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.StampsAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test StampsAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void StampsAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.StampsAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test StampsAccountCarrierGetAccountUrl
        /// </summary>
        [Test]
        public void StampsAccountCarrierGetAccountUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //StampsAccountUrlsRequest stampsAccountUrlsRequest = null;
            //string apiKey = null;
            //var response = instance.StampsAccountCarrierGetAccountUrl(carrierId, stampsAccountUrlsRequest, apiKey);
            //Assert.IsInstanceOf<StampsAccountUrlsResponse> (response, "response is StampsAccountUrlsResponse");
        }
        
        /// <summary>
        /// Test UPSAccountCarrierConnectAccount
        /// </summary>
        [Test]
        public void UPSAccountCarrierConnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UPSAccountInformationDTO model = null;
            //string apiKey = null;
            //var response = instance.UPSAccountCarrierConnectAccount(model, apiKey);
            //Assert.IsInstanceOf<ConnectAccountResponseDTO> (response, "response is ConnectAccountResponseDTO");
        }
        
        /// <summary>
        /// Test UPSAccountCarrierDisconnectAccount
        /// </summary>
        [Test]
        public void UPSAccountCarrierDisconnectAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //instance.UPSAccountCarrierDisconnectAccount(carrierId, apiKey);
            
        }
        
        /// <summary>
        /// Test UPSAccountCarrierGetSettings
        /// </summary>
        [Test]
        public void UPSAccountCarrierGetSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //string apiKey = null;
            //var response = instance.UPSAccountCarrierGetSettings(carrierId, apiKey);
            //Assert.IsInstanceOf<UPSAccountSettingsDTO> (response, "response is UPSAccountSettingsDTO");
        }
        
        /// <summary>
        /// Test UPSAccountCarrierUpdateSettings
        /// </summary>
        [Test]
        public void UPSAccountCarrierUpdateSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierId = null;
            //UPSAccountSettingsDTO settings = null;
            //string apiKey = null;
            //instance.UPSAccountCarrierUpdateSettings(carrierId, settings, apiKey);
            
        }
        
    }

}
