/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing AdvancedOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AdvancedOptionsTests
    {
        // TODO uncomment below to declare an instance variable for AdvancedOptions
        //private AdvancedOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AdvancedOptions
            //instance = new AdvancedOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdvancedOptions
        /// </summary>
        [Test]
        public void AdvancedOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdvancedOptions
            //Assert.IsInstanceOfType<AdvancedOptions> (instance, "variable 'instance' is a AdvancedOptions");
        }


        /// <summary>
        /// Test the property 'BillToAccount'
        /// </summary>
        [Test]
        public void BillToAccountTest()
        {
            // TODO unit test for the property 'BillToAccount'
        }
        /// <summary>
        /// Test the property 'BillToCountryCode'
        /// </summary>
        [Test]
        public void BillToCountryCodeTest()
        {
            // TODO unit test for the property 'BillToCountryCode'
        }
        /// <summary>
        /// Test the property 'BillToParty'
        /// </summary>
        [Test]
        public void BillToPartyTest()
        {
            // TODO unit test for the property 'BillToParty'
        }
        /// <summary>
        /// Test the property 'BillToPostalCode'
        /// </summary>
        [Test]
        public void BillToPostalCodeTest()
        {
            // TODO unit test for the property 'BillToPostalCode'
        }
        /// <summary>
        /// Test the property 'ContainsAlcohol'
        /// </summary>
        [Test]
        public void ContainsAlcoholTest()
        {
            // TODO unit test for the property 'ContainsAlcohol'
        }
        /// <summary>
        /// Test the property 'DeliveredDutyPaid'
        /// </summary>
        [Test]
        public void DeliveredDutyPaidTest()
        {
            // TODO unit test for the property 'DeliveredDutyPaid'
        }
        /// <summary>
        /// Test the property 'NonMachinable'
        /// </summary>
        [Test]
        public void NonMachinableTest()
        {
            // TODO unit test for the property 'NonMachinable'
        }
        /// <summary>
        /// Test the property 'SaturdayDelivery'
        /// </summary>
        [Test]
        public void SaturdayDeliveryTest()
        {
            // TODO unit test for the property 'SaturdayDelivery'
        }
        /// <summary>
        /// Test the property 'UseUpsGroundFreightPricing'
        /// </summary>
        [Test]
        public void UseUpsGroundFreightPricingTest()
        {
            // TODO unit test for the property 'UseUpsGroundFreightPricing'
        }
        /// <summary>
        /// Test the property 'FreightClass'
        /// </summary>
        [Test]
        public void FreightClassTest()
        {
            // TODO unit test for the property 'FreightClass'
        }
        /// <summary>
        /// Test the property 'CustomField1'
        /// </summary>
        [Test]
        public void CustomField1Test()
        {
            // TODO unit test for the property 'CustomField1'
        }
        /// <summary>
        /// Test the property 'CustomField2'
        /// </summary>
        [Test]
        public void CustomField2Test()
        {
            // TODO unit test for the property 'CustomField2'
        }
        /// <summary>
        /// Test the property 'CustomField3'
        /// </summary>
        [Test]
        public void CustomField3Test()
        {
            // TODO unit test for the property 'CustomField3'
        }

    }

}
