/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing ChannelAdvisorAccountInformationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChannelAdvisorAccountInformationRequestTests
    {
        // TODO uncomment below to declare an instance variable for ChannelAdvisorAccountInformationRequest
        //private ChannelAdvisorAccountInformationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChannelAdvisorAccountInformationRequest
            //instance = new ChannelAdvisorAccountInformationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChannelAdvisorAccountInformationRequest
        /// </summary>
        [Test]
        public void ChannelAdvisorAccountInformationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChannelAdvisorAccountInformationRequest
            //Assert.IsInstanceOfType<ChannelAdvisorAccountInformationRequest> (instance, "variable 'instance' is a ChannelAdvisorAccountInformationRequest");
        }


        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Test]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }
        /// <summary>
        /// Test the property 'ProfileId'
        /// </summary>
        [Test]
        public void ProfileIdTest()
        {
            // TODO unit test for the property 'ProfileId'
        }
        /// <summary>
        /// Test the property 'ProductIdentifier'
        /// </summary>
        [Test]
        public void ProductIdentifierTest()
        {
            // TODO unit test for the property 'ProductIdentifier'
        }

    }

}
