/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing CreateWebhookRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateWebhookRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateWebhookRequest
        //private CreateWebhookRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateWebhookRequest
            //instance = new CreateWebhookRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateWebhookRequest
        /// </summary>
        [Test]
        public void CreateWebhookRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateWebhookRequest
            //Assert.IsInstanceOfType<CreateWebhookRequest> (instance, "variable 'instance' is a CreateWebhookRequest");
        }


        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
