/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing DHLExpressUkAccountInformationDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DHLExpressUkAccountInformationDTOTests
    {
        // TODO uncomment below to declare an instance variable for DHLExpressUkAccountInformationDTO
        //private DHLExpressUkAccountInformationDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DHLExpressUkAccountInformationDTO
            //instance = new DHLExpressUkAccountInformationDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DHLExpressUkAccountInformationDTO
        /// </summary>
        [Test]
        public void DHLExpressUkAccountInformationDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DHLExpressUkAccountInformationDTO
            //Assert.IsInstanceOfType<DHLExpressUkAccountInformationDTO> (instance, "variable 'instance' is a DHLExpressUkAccountInformationDTO");
        }


        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Test]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Test]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Test]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }

    }

}
