/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing DHLECommerceAccountInformationDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DHLECommerceAccountInformationDTOTests
    {
        // TODO uncomment below to declare an instance variable for DHLECommerceAccountInformationDTO
        //private DHLECommerceAccountInformationDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DHLECommerceAccountInformationDTO
            //instance = new DHLECommerceAccountInformationDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DHLECommerceAccountInformationDTO
        /// </summary>
        [Test]
        public void DHLECommerceAccountInformationDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DHLECommerceAccountInformationDTO
            //Assert.IsInstanceOfType<DHLECommerceAccountInformationDTO> (instance, "variable 'instance' is a DHLECommerceAccountInformationDTO");
        }


        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Test]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Test]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'PickupNumber'
        /// </summary>
        [Test]
        public void PickupNumberTest()
        {
            // TODO unit test for the property 'PickupNumber'
        }
        /// <summary>
        /// Test the property 'FtpUsername'
        /// </summary>
        [Test]
        public void FtpUsernameTest()
        {
            // TODO unit test for the property 'FtpUsername'
        }
        /// <summary>
        /// Test the property 'FtpPassword'
        /// </summary>
        [Test]
        public void FtpPasswordTest()
        {
            // TODO unit test for the property 'FtpPassword'
        }

    }

}
