/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing EbayAccessTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EbayAccessTokenRequestTests
    {
        // TODO uncomment below to declare an instance variable for EbayAccessTokenRequest
        //private EbayAccessTokenRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EbayAccessTokenRequest
            //instance = new EbayAccessTokenRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EbayAccessTokenRequest
        /// </summary>
        [Test]
        public void EbayAccessTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EbayAccessTokenRequest
            //Assert.IsInstanceOfType<EbayAccessTokenRequest> (instance, "variable 'instance' is a EbayAccessTokenRequest");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Test]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }
        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Test]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'PrivateApplicationId'
        /// </summary>
        [Test]
        public void PrivateApplicationIdTest()
        {
            // TODO unit test for the property 'PrivateApplicationId'
        }

    }

}
