/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing ListManifestsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListManifestsRequestTests
    {
        // TODO uncomment below to declare an instance variable for ListManifestsRequest
        //private ListManifestsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListManifestsRequest
            //instance = new ListManifestsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListManifestsRequest
        /// </summary>
        [Test]
        public void ListManifestsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListManifestsRequest
            //Assert.IsInstanceOfType<ListManifestsRequest> (instance, "variable 'instance' is a ListManifestsRequest");
        }


        /// <summary>
        /// Test the property 'WarehouseId'
        /// </summary>
        [Test]
        public void WarehouseIdTest()
        {
            // TODO unit test for the property 'WarehouseId'
        }
        /// <summary>
        /// Test the property 'ShipDateStart'
        /// </summary>
        [Test]
        public void ShipDateStartTest()
        {
            // TODO unit test for the property 'ShipDateStart'
        }
        /// <summary>
        /// Test the property 'ShipDateEnd'
        /// </summary>
        [Test]
        public void ShipDateEndTest()
        {
            // TODO unit test for the property 'ShipDateEnd'
        }
        /// <summary>
        /// Test the property 'CreatedAtStart'
        /// </summary>
        [Test]
        public void CreatedAtStartTest()
        {
            // TODO unit test for the property 'CreatedAtStart'
        }
        /// <summary>
        /// Test the property 'CreatedAtEnd'
        /// </summary>
        [Test]
        public void CreatedAtEndTest()
        {
            // TODO unit test for the property 'CreatedAtEnd'
        }
        /// <summary>
        /// Test the property 'CarrierId'
        /// </summary>
        [Test]
        public void CarrierIdTest()
        {
            // TODO unit test for the property 'CarrierId'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Test]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

    }

}
