/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing MagentoAccountInformationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MagentoAccountInformationRequestTests
    {
        // TODO uncomment below to declare an instance variable for MagentoAccountInformationRequest
        //private MagentoAccountInformationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MagentoAccountInformationRequest
            //instance = new MagentoAccountInformationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MagentoAccountInformationRequest
        /// </summary>
        [Test]
        public void MagentoAccountInformationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MagentoAccountInformationRequest
            //Assert.IsInstanceOfType<MagentoAccountInformationRequest> (instance, "variable 'instance' is a MagentoAccountInformationRequest");
        }


        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Test]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }
        /// <summary>
        /// Test the property 'StoreUrl'
        /// </summary>
        [Test]
        public void StoreUrlTest()
        {
            // TODO unit test for the property 'StoreUrl'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

    }

}
