/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing ManifestResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ManifestResponseTests
    {
        // TODO uncomment below to declare an instance variable for ManifestResponse
        //private ManifestResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ManifestResponse
            //instance = new ManifestResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ManifestResponse
        /// </summary>
        [Test]
        public void ManifestResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ManifestResponse
            //Assert.IsInstanceOfType<ManifestResponse> (instance, "variable 'instance' is a ManifestResponse");
        }


        /// <summary>
        /// Test the property 'ManifestId'
        /// </summary>
        [Test]
        public void ManifestIdTest()
        {
            // TODO unit test for the property 'ManifestId'
        }
        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Test]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Test]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }
        /// <summary>
        /// Test the property 'Shipments'
        /// </summary>
        [Test]
        public void ShipmentsTest()
        {
            // TODO unit test for the property 'Shipments'
        }
        /// <summary>
        /// Test the property 'WarehouseId'
        /// </summary>
        [Test]
        public void WarehouseIdTest()
        {
            // TODO unit test for the property 'WarehouseId'
        }
        /// <summary>
        /// Test the property 'SubmissionId'
        /// </summary>
        [Test]
        public void SubmissionIdTest()
        {
            // TODO unit test for the property 'SubmissionId'
        }
        /// <summary>
        /// Test the property 'CarrierId'
        /// </summary>
        [Test]
        public void CarrierIdTest()
        {
            // TODO unit test for the property 'CarrierId'
        }
        /// <summary>
        /// Test the property 'ManifestDownload'
        /// </summary>
        [Test]
        public void ManifestDownloadTest()
        {
            // TODO unit test for the property 'ManifestDownload'
        }

    }

}
