/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing RecognizeShipmentResponseDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecognizeShipmentResponseDTOTests
    {
        // TODO uncomment below to declare an instance variable for RecognizeShipmentResponseDTO
        //private RecognizeShipmentResponseDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecognizeShipmentResponseDTO
            //instance = new RecognizeShipmentResponseDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizeShipmentResponseDTO
        /// </summary>
        [Test]
        public void RecognizeShipmentResponseDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecognizeShipmentResponseDTO
            //Assert.IsInstanceOfType<RecognizeShipmentResponseDTO> (instance, "variable 'instance' is a RecognizeShipmentResponseDTO");
        }


        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'Shipment'
        /// </summary>
        [Test]
        public void ShipmentTest()
        {
            // TODO unit test for the property 'Shipment'
        }
        /// <summary>
        /// Test the property 'Entities'
        /// </summary>
        [Test]
        public void EntitiesTest()
        {
            // TODO unit test for the property 'Entities'
        }

    }

}
