/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing RecognizeShipmentRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecognizeShipmentRequestDTOTests
    {
        // TODO uncomment below to declare an instance variable for RecognizeShipmentRequestDTO
        //private RecognizeShipmentRequestDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecognizeShipmentRequestDTO
            //instance = new RecognizeShipmentRequestDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizeShipmentRequestDTO
        /// </summary>
        [Test]
        public void RecognizeShipmentRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecognizeShipmentRequestDTO
            //Assert.IsInstanceOfType<RecognizeShipmentRequestDTO> (instance, "variable 'instance' is a RecognizeShipmentRequestDTO");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Shipment'
        /// </summary>
        [Test]
        public void ShipmentTest()
        {
            // TODO unit test for the property 'Shipment'
        }

    }

}
