/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing StampsAccountUrlResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StampsAccountUrlResponseTests
    {
        // TODO uncomment below to declare an instance variable for StampsAccountUrlResponse
        //private StampsAccountUrlResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StampsAccountUrlResponse
            //instance = new StampsAccountUrlResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StampsAccountUrlResponse
        /// </summary>
        [Test]
        public void StampsAccountUrlResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StampsAccountUrlResponse
            //Assert.IsInstanceOfType<StampsAccountUrlResponse> (instance, "variable 'instance' is a StampsAccountUrlResponse");
        }


        /// <summary>
        /// Test the property 'UrlType'
        /// </summary>
        [Test]
        public void UrlTypeTest()
        {
            // TODO unit test for the property 'UrlType'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
