/* 
 * ShipEngine
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipEngine.ApiClient.Api;
using ShipEngine.ApiClient.Model;
using ShipEngine.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipEngine.ApiClient.Test
{
    /// <summary>
    ///  Class for testing StampsAccountUrlsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StampsAccountUrlsResponseTests
    {
        // TODO uncomment below to declare an instance variable for StampsAccountUrlsResponse
        //private StampsAccountUrlsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StampsAccountUrlsResponse
            //instance = new StampsAccountUrlsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StampsAccountUrlsResponse
        /// </summary>
        [Test]
        public void StampsAccountUrlsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StampsAccountUrlsResponse
            //Assert.IsInstanceOfType<StampsAccountUrlsResponse> (instance, "variable 'instance' is a StampsAccountUrlsResponse");
        }


        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Test]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }

    }

}
